version: '3.9'

services:
  app:
    build: .
    container_name: bowling-league
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./views:/usr/src/app/views
      - ./public:/usr/src/app/public
    environment:
      NODE_ENV: production
      PORT: 3000
      BUY_IN: 5
      MAX_BOWLERS: 8
      ADMIN_SECRET: MySuperSecretAdminKey