services:
  app:
    build: .
    container_name: bowling-league
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./public:/usr/src/app/public
      - ./views:/usr/src/app/views
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BUY_IN=5
      - MAX_BOWLERS=8
