version: '3.9'

services:
  app:
    build: .
    container_name: bowling-league
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./public:/usr/src/app/public
      - ./views:/usr/src/app/views
      - ./utils:/usr/src/app/utils
      - ./bracket.js:/usr/src/app/bracket.js
    env_file:
      - .env
